/**
 * Typed public env - generated by `bun setup` from the selected modules' `env[]`.
 * Every key is optional here: a missing key is reported by `bun doctor`, never a crash.
 *
 * Expo inlines `EXPO_PUBLIC_*` only when referenced statically
 * (`process.env.EXPO_PUBLIC_X`), so every key is spelled out below -
 * never read them through a dynamic lookup.
 */
import { z } from "zod";

const schema = z.object({
  APP_VARIANT: z.enum(["dev", "preview", "prod"]).default("dev"),
  API_URL: z.string().optional(),
});

export type Env = z.infer<typeof schema>;

/** Expo may inline unset keys as `""`; treat that as "not provided". */
function optional(value: string | undefined): string | undefined {
  return value === "" ? undefined : value;
}

/**
 * Hosts iOS App Transport Security lets through over plain http
 * (`NSAllowsLocalNetworking`): IPs, `localhost`, `*.local`, dot-less names.
 * Anything else - an `expo start --tunnel` host (`*.exp.direct`), a deployed
 * API - must be https or iOS refuses the request.
 */
export function isLocalHost(hostUri: string): boolean {
  const host = hostUri.replace(/:\d+$/, "").toLowerCase();
  return (
    /^\d{1,3}(\.\d{1,3}){3}$/.test(host) ||
    host === "localhost" ||
    host.endsWith(".local") ||
    !host.includes(".")
  );
}

/** Dev hint for the ATS failure mode: an http API on a public host. */
function warnInsecureApiUrl(url: string | undefined): void {
  if (!__DEV__ || !url?.startsWith("http://")) return;
  const host = url.slice("http://".length).split("/")[0] ?? "";
  if (isLocalHost(host)) return;
  console.warn(
    `[env] API_URL ${url} is plain http on a non-local host - iOS (App Transport Security) ` +
      "will block it. Use https (tunnels and deployed APIs support it) or the LAN IP."
  );
}

const raw = {
  APP_VARIANT: optional(process.env.EXPO_PUBLIC_APP_VARIANT),
  API_URL: optional(process.env.EXPO_PUBLIC_API_URL),
};

const result = schema.safeParse(raw);

if (!result.success) {
  throw new Error(
    `Invalid EXPO_PUBLIC_* environment:\n${z.prettifyError(result.error)}\n` +
      "Check .env (see .env.example) and restart with `bun run start -- -c`."
  );
}

export const env: Env = result.data;

/**
 * The `EXPO_PUBLIC_*` keys this build reads and whether each was provided - never the
 * values. Shown in Settings → Developer tools (development builds only).
 */
export const envPresence: readonly { key: string; set: boolean }[] = Object.entries(raw).map(
  ([name, value]) => ({ key: `EXPO_PUBLIC_${name}`, set: value !== undefined })
);

warnInsecureApiUrl(env.API_URL);
