import type { ReactNode } from "react";

import { QueryProvider } from "@/lib/query";
import { ThemeProvider as UiThemeProvider, ToastHost } from "@/components/ui";

/**
 * App-wide provider composition (contract 4).
 *
 * Generated by `bun setup` from module `providers[]` sorted by `order`:
 *
 *   10  storage / env
 *   20  data            (react-query, apollo, swr)
 *   30  auth            (supabase, clerk, better-auth)
 *   40  analytics / crash
 *   50  @/components/ui ThemeProvider (+ React Navigation theme from theme/navigation.ts)
 *   60  i18n
 *   70  payments
 *   80  push
 *   85  consent sheet   (renders after children, above ToastHost)
 *   90  toast host      (ToastHost, mounted after children so it renders on top)
 */
export function Providers({ children }: { children: ReactNode }) {
  return (
    <QueryProvider>
      <UiThemeProvider>
        {children}
        <ToastHost />
      </UiThemeProvider>
    </QueryProvider>
  );
}
